---
version: '3'
services: 
  myhana_express:
    image: store/saplabs/hanaexpress:2.00.054.00.20210603.1
    container_name: myhana_express
    restart: always
    ports:
      - 8090:8090
      - 4390:4390
      - 39013:39013
      - 39017:39017
      - 39041-39045:39041-39045
      - 1128-1129:1128-1129
      - 59013-59014:59013-59014
    privileged: true
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    sysctls:
      - kernel.shmmax=1073741824
      - net.ipv4.ip_local_port_range= 40000 60999
      - kernel.shmmni=32
      - kernel.shmall=8388608
    command: ["--passwords-url", "https://gist.githubusercontent.com/hiimivantang/cf0dbee7a1fdcac4ae2abfcbae825e61/raw/b3c0b870d73d5d768242f727a4c01c681d6943b0/passwords.json", "--agree-to-sap-license"]
